covid-api:
  baseUrl: https://api.covid19api.com

spring:
  cache:
    type: caffeine
    caffeine:
      spec:
        maximumSize: 100
        expireAfterWrite: 3600s
server:
  servlet:
    context-path: /api
